// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderApi.Infrastructure;

#nullable disable

namespace OrderApi.Infrastructure.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20260412225823_FixDecimalPrecision")]
    partial class FixDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IdempotencyRecord_CreatedAt");

                    b.ToTable("idempotency_record", (string)null);
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.Order", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("CustomerId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("ResellerId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("StatusId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .IsDescending()
                        .HasDatabaseName("CreatedDate");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("CustomerId");

                    b.HasIndex("ResellerId")
                        .HasDatabaseName("ResellerId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("StatusId");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderItem", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("OrderId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("ProductId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<byte[]>("ServiceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ProductId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ServiceId");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderProduct", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("ServiceId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("order_service_opfk_1");

                    b.ToTable("order_product", (string)null);
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderService", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("order_service", (string)null);
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderStatus", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("Status");

                    b.ToTable("order_status", (string)null);
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderStatusHistory", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("FromStatusId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("OrderId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("ToStatusId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("OrderStatusHistory_OrderId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("order_status_history", (string)null);
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.Order", b =>
                {
                    b.HasOne("OrderApi.Infrastructure.Entities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("order_ofk_1");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderItem", b =>
                {
                    b.HasOne("OrderApi.Infrastructure.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_item_oifk_1");

                    b.HasOne("OrderApi.Infrastructure.Entities.OrderProduct", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("order_product_oifk_1");

                    b.HasOne("OrderApi.Infrastructure.Entities.OrderService", "Service")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("order_service_oifk_1");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderProduct", b =>
                {
                    b.HasOne("OrderApi.Infrastructure.Entities.OrderService", "Service")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("order_service_opfk_1");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("OrderApi.Infrastructure.Entities.OrderStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .IsRequired();

                    b.HasOne("OrderApi.Infrastructure.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderApi.Infrastructure.Entities.OrderStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("Order");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderProduct", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderService", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("OrderApi.Infrastructure.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
